services:
  - type: web
    name: onda-backend
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CHARSET
        value: utf8mb4
